### ISSUE TITLE
lagging video frames

### ISSUE THREAD

**Issue by axpence** [axpence/alexspencer.me#10]
For some reason video frames are lagging on hover. See demo below:
http://www.giphy.com/gifs/xUPGcn678PqWFCVxmM

Is the site using too much memory to load assets? how to reduce ?

Video is expensive bandwidth wise. ideas?

**Comment by makunomark** [comment]
I started getting the lags as well.

**Comment by makunomark** [comment]
I have known what brings about the lag. I tried commenting out some projects and remained with the first 5 and the lag was gone. I suppose loading the projects in batches of 6 will help resolve this

**Comment by axpence** [comment]
https://www.npmjs.com/package/react-lazy-load

Maybe lazy loading would help?

**Comment by makunomark** [comment]
Will look at it. Dude! Js has modules for everything!!

**Comment by axpence** [comment]
https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/

Having modules for everything is Both a blessing and a curse 🤔🤣🙃🙃🙃🙃

**Comment by makunomark** [comment]
Depends on how you look at it. Curse cause its too much to decide from,
blessing since everything has been done, sort of

**Comment by makunomark** [comment]
Lets close this :-)
